#
# Copyright(C) 2014 Pedro H. Penna <pedrohenriquepenna@gmail.com>
#

# Builds everything.
all: release debug

# Builds release version.
release:
	cd genetic-algorithm && $(MAKE) release

# Builds debug version.
debug:
	cd genetic-algorithm && $(MAKE) debug
	
# Cleans compilation files.
clean:
	cd genetic-algorithm && $(MAKE) clean
